import type { CSSProperties, PointerEvent as ReactPointerEvent } from 'react';
import Image from 'next/image';
import { PaidInvoiceStamp } from './paid-invoice-stamp';
import { defaultElementProperties, type DocumentDesign } from '@/lib/document-design';
type Data = Record<string, string | number | boolean>;
export type TemplateBranding = {name:string;logoData:string;rightLogoData?:string;phone:string;email?:string;trn:string;addressLine1:string;addressLine2:string;city:string;country:string};
export function CustomInvoiceTemplate({design,record,lines,setup,contact,target='screen',editable=false,onMoveElement}:{design:DocumentDesign;record:Data;lines:Data[];setup:TemplateBranding;contact?:Data|null;target?:'screen'|'print';editable?:boolean;onMoveElement?:(key:string,x:number,y:number)=>void}) {
 const movable=(key:string)=>!key.startsWith('columns.');
 const properties=(key:string):CSSProperties=>{
  const p=design.properties?.[key];
  if(!p)return editable&&movable(key)?{cursor:'move',touchAction:'none',position:'relative',zIndex:1}:{};
  const border=`${p.thickness}pt ${p.pattern} ${p.borderColor}`;
  return {textAlign:p.align,verticalAlign:p.vertical,alignContent:p.vertical==='middle'?'center':p.vertical==='bottom'?'end':'start',fontFamily:p.font,fontSize:p.size,fontWeight:p.bold?700:400,fontStyle:p.italic?'italic':'normal',textDecoration:p.underline?'underline':'none',color:p.color,borderTop:p.top?border:'none',borderRight:p.right?border:'none',borderBottom:p.bottom?border:'none',borderLeft:p.left?border:'none',borderRadius:p.radius,backgroundColor:p.fill?p.background:'transparent',minHeight:p.minHeight||undefined,height:p.boxHeight||((key.startsWith('columns.'))?p.minHeight||undefined:undefined),width:p.boxWidth||undefined,padding:7,transform:(p.offsetX||p.offsetY)?`translate(${p.offsetX}px, ${p.offsetY}px)`:undefined,cursor:editable&&movable(key)?'move':undefined,touchAction:editable&&movable(key)?'none':undefined,position:editable&&movable(key)?'relative':undefined,zIndex:editable&&movable(key)?1:undefined};
 };
 const startDrag=(key:string,event:ReactPointerEvent<HTMLElement>)=>{
  if(!editable||!onMoveElement||!movable(key)||event.button!==0)return;
  event.preventDefault();
  event.stopPropagation();
  const base=design.properties?.[key]||defaultElementProperties;
  const startX=event.clientX;
  const startY=event.clientY;
  const move=(next:PointerEvent)=>onMoveElement(key,Math.max(-1200,Math.min(1200,Math.round(base.offsetX+next.clientX-startX))),Math.max(-1600,Math.min(1600,Math.round(base.offsetY+next.clientY-startY))));
  const stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);window.removeEventListener('pointercancel',stop);};
  window.addEventListener('pointermove',move);
  window.addEventListener('pointerup',stop,{once:true});
  window.addEventListener('pointercancel',stop,{once:true});
 };
 const editableClass=(key:string,base='')=>`${base}${editable&&movable(key)?`${base?' ':''}ci-editable`:''}`;
 const headers=design.headers.filter(f=>f[target]); const columns=design.columns.filter(f=>f[target]); const footer=design.footer.filter(f=>f[target]);
 const money=(v:unknown)=>Number(v||0).toLocaleString('en-US',{minimumFractionDigits:design.decimals,maximumFractionDigits:design.decimals});
 const values:Record<string,unknown>={number:record.number,date:record.transactionDate,billTo:contact?.billingName||contact?.company||record.party,shipTo:record.deliveryAddress||contact?.shippingAddress||contact?.country||'',terms:record.terms||contact?.paymentTerms||'',dueDate:record.dueDate,salesman:record.salesman,trn:setup.trn,source:record.sourceDocumentNumber||'',subtotal:record.subtotal,vatAmount:record.vatAmount,total:record.total,balance:record.balance??(record.status==='paid'?0:record.total),message:design.message,disclaimer:design.disclaimer};
 const textFooter=footer.filter(f=>['message','disclaimer'].includes(f.key));
 return <article className="custom-invoice" style={{fontFamily:design.font,fontSize:design.fontSize,color:'#111',background:'#fff',padding:20}}>
  <style>{`.custom-invoice{line-height:1.45;print-color-adjust:exact;-webkit-print-color-adjust:exact}.custom-invoice *{box-sizing:border-box}.custom-invoice table{width:100%;border-collapse:collapse;table-layout:fixed}.custom-invoice td,.custom-invoice th{border:1px solid #bbb;padding:7px;vertical-align:top;overflow-wrap:anywhere;white-space:pre-wrap}.custom-invoice th{background:#f3f4f6;text-align:left}.custom-invoice p{margin:3px 0;white-space:pre-wrap;overflow-wrap:anywhere}.custom-invoice .ci-head{display:grid;grid-template-columns:1fr 2fr 1fr;gap:12px;align-items:start}.custom-invoice .ci-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0}.custom-invoice .ci-bottom{display:grid;grid-template-columns:3fr 2fr;gap:24px;margin-top:20px}.custom-invoice .ci-total{display:flex;justify-content:space-between;border-bottom:1px solid #ccc;padding:8px 0;gap:15px}.custom-invoice .ci-editable{outline:1px dashed #94a3b8;outline-offset:2px}.custom-invoice .ci-editable:hover{outline:2px solid #2563eb}@media print{.custom-invoice{padding:0!important}.custom-invoice thead{display:table-header-group}.ci-head,.ci-meta,.ci-total{break-inside:avoid}.custom-invoice .ci-editable{outline:none!important}}`}</style>
  <div className="ci-head"><div className={editableClass('leftLogo')} style={properties('leftLogo')} onPointerDown={e=>startDrag('leftLogo',e)}>{design.leftLogo&&setup.logoData&&<Image src={setup.logoData} alt="Left company logo" width={design.logoWidth} height={design.logoHeight} unoptimized style={{width:design.logoWidth,maxWidth:'100%',height:design.logoHeight,objectFit:'contain'}}/>}</div><div style={{textAlign:'center'}}>{design.showCompany&&<p className={editableClass('company')} onPointerDown={e=>startDrag('company',e)} style={{fontSize:design.companySize,fontWeight:700,color:design.color,...properties('company')}}>{setup.name}</p>}{design.showAddress&&<p>{[setup.addressLine1,setup.addressLine2,setup.city,setup.country].filter(Boolean).join(', ')}</p>}{design.showPhone&&setup.phone&&<p>{setup.phone}</p>}{design.showEmail&&setup.email&&<p>{setup.email}</p>}<h2 className={editableClass('title')} onPointerDown={e=>startDrag('title',e)} style={{fontSize:design.titleSize,color:design.color,margin:'12px 0',...properties('title')}}>{design.title}</h2></div><div className={editableClass('rightLogo')} style={{textAlign:'right',...properties('rightLogo')}} onPointerDown={e=>startDrag('rightLogo',e)}>{design.rightLogo&&setup.rightLogoData&&<Image src={setup.rightLogoData} alt="Right company logo" width={design.logoWidth} height={design.logoHeight} unoptimized style={{width:design.logoWidth,maxWidth:'100%',height:design.logoHeight,objectFit:'contain'}}/>}</div></div>
  {design.statusStamp&&<div className={editableClass('status')} style={properties('status')} onPointerDown={e=>startDrag('status',e)}>{record.status === 'paid' ? <PaidInvoiceStamp status="paid" paidAt={record.paidAt ? String(record.paidAt) : null} /> : <p style={{textAlign:'right',fontWeight:700,textTransform:'uppercase'}}>{String(record.status||'')}</p>}</div>}
  <div className="ci-meta">{headers.map(f=><div key={f.key} className={editableClass(`headers.${f.key}`)} onPointerDown={e=>startDrag(`headers.${f.key}`,e)} style={properties(`headers.${f.key}`)}><strong>{f.label}</strong><p>{String(values[f.key]||'—')}</p></div>)}</div>
  <table className={editableClass('itemsTable')} onPointerDown={e=>startDrag('itemsTable',e)} style={{...(Object.values(design.properties||{}).some(p=>p.radius>0)?{borderCollapse:'separate',borderSpacing:0}:{}),...properties('itemsTable')}}><colgroup>{columns.map(c=><col key={c.key} style={{width:`${c.width/columns.reduce((s,c)=>s+c.width,0)*100}%`}}/>)}</colgroup><thead><tr>{columns.map(c=><th key={c.key} style={properties(`columns.${c.key}`)}>{c.label}</th>)}</tr></thead><tbody>{lines.map((line,i)=><tr key={String(line.id||i)}>{columns.map(c=><td key={c.key} style={properties(`columns.${c.key}`)}>{['unitPrice','subtotal','vatAmount','total'].includes(c.key)?money(line[c.key]):String(line[c.key]??'')}</td>)}</tr>)}</tbody></table>
  <div className="ci-bottom"><div className={editableClass('footerText')} style={properties('footerText')} onPointerDown={e=>startDrag('footerText',e)}>{textFooter.map(f=><div key={f.key} className={editableClass(`footer.${f.key}`)} onPointerDown={e=>startDrag(`footer.${f.key}`,e)} style={properties(`footer.${f.key}`)}><strong>{f.label}</strong><p>{String(values[f.key]||'')}</p></div>)}</div><div className={editableClass('totals')} style={properties('totals')} onPointerDown={e=>startDrag('totals',e)}>{footer.filter(f=>!['message','disclaimer'].includes(f.key)).map(f=><div key={f.key} className={editableClass(`footer.${f.key}`,'ci-total')} onPointerDown={e=>startDrag(`footer.${f.key}`,e)} style={properties(`footer.${f.key}`)}><strong>{f.label} ({String(record.currency||'AED')})</strong><span>{money(values[f.key])}</span></div>)}</div></div>
 </article>;
}
