import type { CSSProperties } from 'react';
import Image from 'next/image';
import { PaidInvoiceStamp } from './paid-invoice-stamp';
import { type DocumentDesign } from '@/lib/document-design';
type Data = Record<string, string | number | boolean>;
export type TemplateBranding = {name:string;logoData:string;rightLogoData?:string;phone:string;email?:string;trn:string;addressLine1:string;addressLine2:string;city:string;country:string};
export function CustomInvoiceTemplate({design,record,lines,setup,contact,target='screen'}:{design:DocumentDesign;record:Data;lines:Data[];setup:TemplateBranding;contact?:Data|null;target?:'screen'|'print'}) {
 const properties=(key:string):CSSProperties=>{
  const p=design.properties?.[key];
  if(!p)return {};
  const border=`${p.thickness}pt ${p.pattern} ${p.borderColor}`;
  return {textAlign:p.align,verticalAlign:p.vertical,alignContent:p.vertical==='middle'?'center':p.vertical==='bottom'?'end':'start',fontFamily:p.font,fontSize:p.size,fontWeight:p.bold?700:400,fontStyle:p.italic?'italic':'normal',textDecoration:p.underline?'underline':'none',color:p.color,borderTop:p.top?border:'none',borderRight:p.right?border:'none',borderBottom:p.bottom?border:'none',borderLeft:p.left?border:'none',borderRadius:p.radius,backgroundColor:p.fill?p.background:'transparent',minHeight:p.minHeight||undefined,height:key.startsWith('columns.')?p.minHeight||undefined:undefined,padding:7};
 };
 const headers=design.headers.filter(f=>f[target]); const columns=design.columns.filter(f=>f[target]); const footer=design.footer.filter(f=>f[target]);
 const money=(v:unknown)=>Number(v||0).toLocaleString('en-US',{minimumFractionDigits:design.decimals,maximumFractionDigits:design.decimals});
 const values:Record<string,unknown>={number:record.number,date:record.transactionDate,billTo:contact?.billingName||contact?.company||record.party,shipTo:record.deliveryAddress||contact?.shippingAddress||contact?.country||'',terms:record.terms||contact?.paymentTerms||'',dueDate:record.dueDate,salesman:record.salesman,trn:setup.trn,source:record.sourceDocumentNumber||'',subtotal:record.subtotal,vatAmount:record.vatAmount,total:record.total,balance:record.balance??(record.status==='paid'?0:record.total),message:design.message,disclaimer:design.disclaimer};
 const textFooter=footer.filter(f=>['message','disclaimer'].includes(f.key));
 return <article className="custom-invoice" style={{fontFamily:design.font,fontSize:design.fontSize,color:'#111',background:'#fff',padding:20}}>
  <style>{`.custom-invoice{line-height:1.45;print-color-adjust:exact;-webkit-print-color-adjust:exact}.custom-invoice *{box-sizing:border-box}.custom-invoice table{width:100%;border-collapse:collapse;table-layout:fixed}.custom-invoice td,.custom-invoice th{border:1px solid #bbb;padding:7px;vertical-align:top;overflow-wrap:anywhere;white-space:pre-wrap}.custom-invoice th{background:#f3f4f6;text-align:left}.custom-invoice p{margin:3px 0;white-space:pre-wrap;overflow-wrap:anywhere}.custom-invoice .ci-head{display:grid;grid-template-columns:1fr 2fr 1fr;gap:12px;align-items:start}.custom-invoice .ci-meta{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:24px 0}.custom-invoice .ci-bottom{display:grid;grid-template-columns:3fr 2fr;gap:24px;margin-top:20px}.custom-invoice .ci-total{display:flex;justify-content:space-between;border-bottom:1px solid #ccc;padding:8px 0;gap:15px}@media print{.custom-invoice{padding:0!important}.custom-invoice thead{display:table-header-group}.ci-head,.ci-meta,.ci-total{break-inside:avoid}}`}</style>
  <div className="ci-head"><div>{design.leftLogo&&setup.logoData&&<Image src={setup.logoData} alt="Left company logo" width={design.logoWidth} height={design.logoHeight} unoptimized style={{width:design.logoWidth,maxWidth:'100%',height:design.logoHeight,objectFit:'contain'}}/>}</div><div style={{textAlign:'center'}}>{design.showCompany&&<p style={{fontSize:design.companySize,fontWeight:700,color:design.color,...properties('company')}}>{setup.name}</p>}{design.showAddress&&<p>{[setup.addressLine1,setup.addressLine2,setup.city,setup.country].filter(Boolean).join(', ')}</p>}{design.showPhone&&setup.phone&&<p>{setup.phone}</p>}{design.showEmail&&setup.email&&<p>{setup.email}</p>}<h2 style={{fontSize:design.titleSize,color:design.color,margin:'12px 0',...properties('title')}}>{design.title}</h2></div><div style={{textAlign:'right'}}>{design.rightLogo&&setup.rightLogoData&&<Image src={setup.rightLogoData} alt="Right company logo" width={design.logoWidth} height={design.logoHeight} unoptimized style={{width:design.logoWidth,maxWidth:'100%',height:design.logoHeight,objectFit:'contain'}}/>}</div></div>
  {design.statusStamp&&(record.status === 'paid' ? <PaidInvoiceStamp status="paid" paidAt={record.paidAt ? String(record.paidAt) : null} /> : <p style={{textAlign:'right',fontWeight:700,textTransform:'uppercase'}}>{String(record.status||'')}</p>)}
  <div className="ci-meta">{headers.map(f=><div key={f.key} style={properties(`headers.${f.key}`)}><strong>{f.label}</strong><p>{String(values[f.key]||'—')}</p></div>)}</div>
  <table style={Object.values(design.properties||{}).some(p=>p.radius>0)?{borderCollapse:'separate',borderSpacing:0}:undefined}><colgroup>{columns.map(c=><col key={c.key} style={{width:`${c.width/columns.reduce((s,c)=>s+c.width,0)*100}%`}}/>)}</colgroup><thead><tr>{columns.map(c=><th key={c.key} style={properties(`columns.${c.key}`)}>{c.label}</th>)}</tr></thead><tbody>{lines.map((line,i)=><tr key={String(line.id||i)}>{columns.map(c=><td key={c.key} style={properties(`columns.${c.key}`)}>{['unitPrice','subtotal','vatAmount','total'].includes(c.key)?money(line[c.key]):String(line[c.key]??'')}</td>)}</tr>)}</tbody></table>
  <div className="ci-bottom"><div>{textFooter.map(f=><div key={f.key} style={properties(`footer.${f.key}`)}><strong>{f.label}</strong><p>{String(values[f.key]||'')}</p></div>)}</div><div>{footer.filter(f=>!['message','disclaimer'].includes(f.key)).map(f=><div key={f.key} className="ci-total" style={properties(`footer.${f.key}`)}><strong>{f.label} ({String(record.currency||'AED')})</strong><span>{money(values[f.key])}</span></div>)}</div></div>
 </article>;
}
