"use client";

type Account = { id: number; name?: unknown; code?: unknown; type?: unknown; active?: unknown; systemRole?: unknown; currency?: unknown };

export function EmployeeHrFields({ form, onChange, accounts }: { form: Record<string, string>; onChange: (form: Record<string, string>) => void; accounts: Account[] }) {
  const expenses = accounts.filter(account => account.active && account.type === "Expense");
  const loanAccounts = accounts.filter(account => account.active && account.type === "Other Current Asset" && !account.systemRole && account.currency === (form.currency || "AED"));
  const fallback = expenses.find(account => account.systemRole === "PAYROLL");
  const update = (key: string, value: string) => onChange({ ...form, [key]: value });
  return <section className="employee-hr-fields sm:col-span-2"><h3>Salary, loan & vacation</h3><p>Amounts in {form.currency || "AED"}. Saving this profile does not post a payment or loan transaction.</p><div className="grid gap-4 sm:grid-cols-2"><label>Monthly salary<input type="number" min="0" max="1000000000000" step="0.01" value={form.salaryAmount || "0"} onChange={event => update("salaryAmount", event.target.value)} /></label><label>Manual loan balance<input type="number" min="0" max="1000000000000" step="0.01" value={form.loanBalance || "0"} onChange={event => update("loanBalance", event.target.value)} /></label><label className="sm:col-span-2">Salary expense account<select value={form.salaryExpenseAccountId || String(fallback?.id || "")} onChange={event => update("salaryExpenseAccountId", event.target.value)}><option value="">Select salary expense account</option>{expenses.map(account => <option key={account.id} value={account.id}>{String(account.code)} · {String(account.name)}</option>)}</select></label><label className="sm:col-span-2">Loan / advance account<select value={form.loanAccountId || ""} onChange={event => update("loanAccountId", event.target.value)}><option value="">Select loan / advance account</option>{form.loanAccountId && !loanAccounts.some(account => String(account.id) === form.loanAccountId) && <option value={form.loanAccountId} disabled>Linked account unavailable — choose another</option>}{loanAccounts.map(account => <option key={account.id} value={account.id}>{String(account.code)} · {String(account.name)} · {String(account.currency)}</option>)}</select><span className="text-xs font-normal text-muted-foreground">Links this employee to their loan receivable account. Banking employee-loan payments use this account automatically.</span>{loanAccounts.length === 0 && <span role="status" className="text-xs font-normal text-amber-700 dark:text-amber-300">No eligible account. Add an active Other Current Asset account in {form.currency || "AED"} under Chart of Accounts, then reopen this employee.</span>}</label><label>Vacation departure date<input type="date" value={form.vacationDeparture || ""} onChange={event => update("vacationDeparture", event.target.value)} /></label><label>Vacation return date<input type="date" min={form.vacationDeparture || undefined} value={form.vacationReturn || ""} onChange={event => update("vacationReturn", event.target.value)} /></label></div><p>Salary cheques for this employee use the linked expense account. Create a payment in Banking → Write Cheque → Employee loan to link it here automatically. Keep the manual balance separate; linked payments are not added to it.</p><EmployeeBankLoans value={form.bankLoanPayments} /></section>;
}

export function EmployeeHrDetails({ record, accounts }: { record: Record<string, unknown>; accounts: Account[] }) {
  const account = accounts.find(account => account.id === Number(record.salaryExpenseAccountId));
  const loanAccount = accounts.find(account => account.id === Number(record.loanAccountId));
  const amount = (value: unknown) => `${String(record.currency || "AED")} ${Number(value || 0).toLocaleString("en-AE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  return <><dl className="employee-hr-details"><div><dt>Monthly salary</dt><dd>{amount(record.salaryAmount)}</dd></div><div><dt>Manual loan</dt><dd>{amount(record.loanBalance)}</dd></div><div><dt>Salary account</dt><dd>{account ? `${account.code} · ${account.name}` : "Not configured"}</dd></div><div><dt>Loan / advance account</dt><dd>{loanAccount ? `${loanAccount.code} · ${loanAccount.name}` : "Not configured"}</dd></div><div><dt>Vacation departure</dt><dd>{String(record.vacationDeparture || "—")}</dd></div><div><dt>Vacation return</dt><dd>{String(record.vacationReturn || "—")}</dd></div></dl><EmployeeBankLoans value={record.bankLoanPayments} /></>;
}


type LoanPayment = { id: number; number: string; date: string; currency: string; amount: number; account: string };
function EmployeeBankLoans({ value }: { value: unknown }) {
  let payments: LoanPayment[] = [];
  try { const parsed: unknown = JSON.parse(String(value || "[]")); if (Array.isArray(parsed)) payments = parsed; } catch { /* New employee has no linked loans. */ }
  const totals = new Map<string, number>();
  for (const payment of payments) totals.set(payment.currency, (totals.get(payment.currency) || 0) + Number(payment.amount));
  return <div className="mt-4 min-w-0 rounded-xl border border-border bg-background p-3 text-foreground">
    <h4 className="text-sm font-semibold">Linked bank loan payments</h4>
    {payments.length ? <><p className="mt-1 text-sm font-semibold tabular-nums">{Array.from(totals, ([currency, amount]) => `${currency} ${amount.toLocaleString("en-AE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`).join(" · ")}</p><p className="text-xs text-muted-foreground">Total paid from Banking. Repayments and salary deductions are not included.</p><details className="mt-2"><summary className="cursor-pointer text-sm">View {payments.length} payment{payments.length === 1 ? "" : "s"}</summary><ul className="mt-2 max-h-64 space-y-2 overflow-y-auto">{payments.map(payment => <li key={payment.id} className="rounded-lg bg-muted p-2 text-xs whitespace-normal break-words"><strong>{payment.number}</strong> · {payment.date}<br />{payment.currency} {Number(payment.amount).toLocaleString("en-AE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} · {payment.account}</li>)}</ul></details></> : <p className="mt-1 text-xs text-muted-foreground">No linked bank loan payments. Choose Employee loan in Banking and select this employee when making the payment.</p>}
  </div>;
}
