"use client";

import { ArrowUpRight } from "lucide-react";
import { listReportGroups, emptyListFilters, type ListFilters } from "@/lib/list-report";
import type { ReportColumn, ReportRow } from "@/lib/report-presentation";

export function ListReportLibrary({ reports, loading, onOpen }: { reports: Array<{ key: string; name: string; description: string }>; loading: boolean; onOpen: (key: string) => void }) {
  const unique = [...new Map(reports.map(report => [report.key, report])).values()];
  return <div className="list-library"><div className="pnl-library-intro"><p className="pnl-eyebrow">Reference library</p><h4>Find the records behind your business.</h4><p>Browse accounts, items, contact directories and working records. Search within a report, follow verified account links and export the rows you need.</p><div className="pnl-library-tags"><span>Linked accounts</span><span>A4 print & PDF</span><span>Excel & CSV</span></div></div>{listReportGroups.map(group => { const items = unique.filter(report => group.keys.includes(report.key)); return items.length ? <section className="list-library-group" key={group.title}><h5>{group.title}</h5><p>{group.description}</p><div className="pnl-library-cards">{items.map(report => <button type="button" key={report.key} disabled={loading} onClick={() => onOpen(report.key)}><span><strong>{report.name}</strong><small>{report.description}</small></span><ArrowUpRight className="size-5 shrink-0" aria-hidden="true" /></button>)}</div></section> : null; })}</div>;
}

export function ListReportFilters({ rows, columns, filters, onChange, visibleCount }: { rows: ReportRow[]; columns: ReportColumn[]; filters: ListFilters; onChange: (filters: ListFilters) => void; visibleCount: number }) {
  const statuses = [...new Set(rows.map(row => String(row.status || "")).filter(Boolean))].sort();
  return <section className="list-filters accountant-filters" aria-label="List report filters"><div className="list-filter-controls accountant-filter-controls print:hidden"><label>Search report<input type="search" value={filters.query} placeholder="Name, SKU, account or contact details" onChange={event => onChange({ ...filters, query: event.target.value })} /></label>{statuses.length > 0 && <label>Status<select value={filters.status} onChange={event => onChange({ ...filters, status: event.target.value })}><option value="">All statuses</option>{statuses.map(status => <option key={status}>{status}</option>)}</select></label>}<label>Sort by<select value={filters.sort} onChange={event => onChange({ ...filters, sort: event.target.value })}><option value="">Original order</option>{columns.flatMap(column => [<option key={`${column.key}:asc`} value={`${column.key}:asc`}>{column.label} · ascending</option>, <option key={`${column.key}:desc`} value={`${column.key}:desc`}>{column.label} · descending</option>])}</select></label><button type="button" disabled={!filters.query && !filters.status && !filters.sort} onClick={() => onChange({ ...emptyListFilters })}>Clear filters</button></div><p role="status">Showing {visibleCount} of {rows.length} records · summaries, print and downloads use these rows.{filters.query ? ` Search: ${filters.query}.` : ""}{filters.status ? ` Status: ${filters.status}.` : ""}</p></section>;
}
