import Image from "next/image";

type RecordData = Record<string, string | number | boolean>;
type Branding = { name: string; logoData: string; phone: string; trn: string; addressLine1: string; addressLine2: string; city: string; country: string };
export const salesDocumentTitles = {
  "tax-invoice": ["Tax Invoice", "فاتورة ضريبية", "Invoice# / رقم الفاتورة"],
  quotation: ["Quotation", "عرض سعر", "Quotation# / رقم عرض السعر"],
  "sales-order": ["Sales Order", "أمر بيع", "Order# / رقم الطلب"],
  "cash-sales": ["Cash Sales", "مبيعات نقدية", "Receipt# / رقم الإيصال"],
} as const;
export type SalesDocumentMode = keyof typeof salesDocumentTitles;

// Shared by the screen preview, standalone download, and print window.
export const salesDocumentCss = `
.sales-document{font:13px Arial,sans-serif;color:#111;background:#fff;padding:22px;width:100%;box-sizing:border-box;line-height:1.35}
.sales-document *{box-sizing:border-box}.sales-document p{margin:0}.sales-document .sd-header{display:grid;grid-template-columns:1fr 1fr 1fr;gap:18px;align-items:start;min-height:125px}.sd-logo{width:240px;height:70px;object-fit:contain;object-position:left center}.sd-brand{font-size:28px;font-weight:700;color:#df3834;line-height:1.1}.sd-phone{font-weight:bold;margin-top:8px!important}.sd-title{margin:0;text-align:center;color:#aaa;font-size:30px;font-weight:700;line-height:1.2}.sd-arabic-brand{text-align:right;font-size:46px;font-weight:900;line-height:1.2}.sd-arabic-brand small{display:block;font-size:20px;color:#e52323}.sd-address{font-size:10px;margin-top:7px!important}.sd-parties{display:grid;grid-template-columns:1fr 1fr;gap:24px;min-height:145px;padding:14px 0 30px}.sd-parties h3{font-size:19px;text-decoration:underline;font-style:italic;margin:0 0 5px}.sd-parties p{white-space:pre-line}.sd-delivery{text-align:right}.sd-meta{display:grid;grid-template-columns:1fr 1.2fr 1fr 1.2fr 1.3fr 1.25fr}.sd-meta>div{border:1px solid #bbb;border-radius:10px 10px 0 0;padding:9px 5px;text-align:center;overflow-wrap:anywhere}.sd-meta b{display:block}.sales-document table{width:100%;border-collapse:collapse;table-layout:fixed}.sales-document th,.sales-document td{border:1px solid #bbb;padding:9px 6px;vertical-align:top;overflow-wrap:anywhere}.sales-document th{text-align:center;font-size:14px}.sales-document td{text-align:right}.sales-document td:first-child{text-align:left;font-weight:700;white-space:pre-line}.sd-items tbody tr:last-child{height:78px}.sd-items small{display:block;font-size:10px;font-weight:400}.sd-bottom{display:grid;grid-template-columns:59% 41%;align-items:start}.sd-terms{padding:14px 22px 0 0;font-size:10px}.sd-terms h3{font-size:15px;text-decoration:underline;margin:0 0 12px}.sd-terms ul,.sd-arabic-terms ul{padding-inline-start:16px;margin:0;list-style:disc}.sd-totals{border:1px solid #bbb;padding:5px 16px}.sd-totals>div{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #bbb;font-weight:bold;font-size:14px}.sd-totals>div:last-child{border:0}.sd-totals strong{font-size:20px;white-space:nowrap}.sd-arabic-terms{font-size:12px;padding-top:15px}.sd-signature{margin-top:35px!important;font-size:11px}.sd-note{margin-top:12px!important;white-space:pre-line;font-size:11px}.sd-extra{font-size:10px;font-weight:normal;margin-top:4px}.sd-notice{font-size:11px;margin-top:8px!important}
@media(max-width:700px){.sales-document{padding:12px}.sd-title{font-size:20px}.sd-brand{font-size:21px}.sd-arabic-brand{font-size:30px}.sd-logo{width:100%;height:60px}.sd-meta{grid-template-columns:repeat(3,1fr)}.sd-bottom{grid-template-columns:1fr}.sd-terms{padding-right:0;padding-bottom:18px}}
@page{size:A4;margin:10mm}@media print{.sales-document{padding:0;font-size:10px}.sales-document .sd-header{min-height:100px}.sd-title{font-size:25px}.sd-parties{min-height:125px}.sd-meta{grid-template-columns:1fr 1.2fr 1fr 1.2fr 1.3fr 1.25fr}.sd-bottom{grid-template-columns:59% 41%}.sales-document th{font-size:11px}.sd-totals>div{font-size:11px}.sd-totals strong{font-size:17px}.sd-terms{font-size:9px;padding-right:18px}.sd-arabic-terms{font-size:10px}.sales-document tr,.sd-meta,.sd-totals,.sd-signature{break-inside:avoid}.sales-document thead{display:table-header-group}.sd-logo{width:210px}.sd-header,.sd-parties{break-inside:avoid}}
`;

export function SalesDocumentTemplate({ mode, record, lines, contact, setup, showBillingName, showShipping, showHsCode, showDimensions }: { mode: SalesDocumentMode; record: RecordData; lines: RecordData[]; contact?: RecordData | null; setup: Branding; showBillingName: boolean; showShipping: boolean; showHsCode: boolean; showDimensions: boolean }) {
  const [title, arabic, numberLabel] = salesDocumentTitles[mode];
  const money = (value: unknown) => Number(value || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const currency = String(record.currency || "AED");
  const isCash = record.type === "sales receipt";
  const isProposal = mode === "quotation" || mode === "sales-order";
  const comnet = /comnet/i.test(setup.name);
  const dateText = String(record.transactionDate || "");
  const dateParts = /^(\d{4})-(\d{2})-(\d{2})/.exec(dateText);
  const invoiceDate = dateParts ? `${dateParts[3]}/${["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][Number(dateParts[2]) - 1]}/${dateParts[1]}` : dateText;
  const metadata = [[numberLabel, record.number], ["Date / التاريخ", invoiceDate], ["Terms / شروط", record.terms || contact?.paymentTerms || (isCash ? "Cash" : "—")], [mode === "quotation" ? "Valid Until / صالح حتى" : "Due Date / تاريخ الاستحقاق", record.dueDate || "—"], ["Sales Rep. / رجل المبيعات", record.salesman || "—"], ["TRN / الرقم الضريبي", setup.trn || "—"]];
  return <article className="sales-document" aria-label={`${title} ${record.number}`}>
    <style>{salesDocumentCss}</style>
    <div className="sd-header">
      <div>{setup.logoData ? <Image className="sd-logo" src={setup.logoData} alt={`${setup.name} logo`} width={240} height={70} unoptimized /> : <div className="sd-brand">{setup.name}</div>}{setup.phone && <p className="sd-phone">{setup.phone}</p>}<p className="sd-address">{[setup.addressLine1, setup.addressLine2, setup.city, setup.country].filter(Boolean).join(", ")}</p></div>
      <h2 className="sd-title"><span lang="ar" dir="rtl">{arabic}</span><br />{title}</h2>
      {comnet ? <div className="sd-arabic-brand" lang="ar" dir="rtl">كومنيت<small>انترناشيونال ذ م م</small></div> : <div />}
    </div>
    <div className="sd-parties"><div>{showBillingName && <><h3>Customer: <span lang="ar" dir="rtl">العميل</span></h3><p>{String(contact?.billingName || contact?.company || record.party)}</p>{contact?.trn && <p>TRN: {String(contact.trn)}</p>}{contact?.phone && <p>{String(contact.phone)}</p>}</>}</div><div className="sd-delivery">{showShipping && <><h3>Delivery Address: <span lang="ar" dir="rtl">عنوان التسليم</span></h3><p>{String(record.deliveryAddress || contact?.deliveryAddress || contact?.shippingAddress || "")}</p></>}</div></div>
    <div className="sd-meta">{metadata.map(([label, value]) => <div key={String(label)}><b>{label}</b>{value}</div>)}</div>
    <table className="sd-items"><colgroup><col style={{ width: "73%" }} /><col style={{ width: "5%" }} /><col style={{ width: "6%" }} /><col style={{ width: "6%" }} /><col style={{ width: "6%" }} /><col style={{ width: "4%" }} /></colgroup><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Inc. VAT</th><th>Sub Total</th><th>VAT</th></tr></thead><tbody>{lines.map((line, index) => <tr key={String(line.id || index)}><td>{String(line.description || "")}{line.sku ? <small>{String(line.sku)}</small> : null}{showHsCode && <div className="sd-extra">HS Code: {String(line.hsCode || "—")} · COO: {String(line.countryOfOrigin || "—")}</div>}{showDimensions && <div className="sd-extra">Dimensions: {String(line.dimensionText || "—")} · Weight: {String(line.weightKg || "—")} kg</div>}</td><td>{line.quantity}</td><td>{money(line.unitPrice)}</td><td>{money(Number(line.quantity) ? Number(line.total) / Number(line.quantity) : 0)}</td><td>{money(line.subtotal)}</td><td>{money(line.vatAmount)}<small>{Number(line.vatRate || 0)}%</small></td></tr>)}</tbody></table>
    <div className="sd-bottom"><div className="sd-terms"><h3>Terms &amp; Conditions</h3><ul><li>The warranty is covered by showroom only (no international or service center warranty). Software, accessories, batteries and consumables are not covered. Please retain the sales invoice to claim warranty.</li><li>No replacement for warranty claims except products not working out of the box and returned within 3 days of invoice date.</li><li><b>Warranty Types:</b> <i>Brand New = 1 YEAR, Open Box &amp; Refurbished = 90 Days (starting by invoice date).</i></li><li>Warranty is void if the seal is broken or the device is opened. Warranty claims may take 35–45 days to return.</li><li>If the device is not repairable, a refund will be provided after deduction of 4% per month starting from the invoice date.</li><li>Warranty is void if there is physical damage or any dent.</li><li><b>I agree with all the above warranty terms &amp; conditions.</b></li></ul>{isProposal && <p className="sd-notice">Warranty starts from the final invoice date. This {mode === "quotation" ? "quotation" : "sales order"} is not a tax invoice.</p>}<p className="sd-signature">Customer Signature: ____________________ <span lang="ar" dir="rtl">توقيع العميل</span></p></div>
    <div><div className="sd-totals"><div><span>Subtotal ({currency}) / حاصل الجمع</span><strong>{money(record.subtotal)}</strong></div><div><span>Total VAT / ضريبة القيمة المضافة</span><strong>{money(record.vatAmount)}</strong></div><div><span>Total ({currency}) / مجموع</span><strong>{money(record.total)}</strong></div>{!isProposal && <div><span>Balance ({currency}) / الرصيد</span><strong>{money(record.balance ?? (isCash || record.status === "paid" ? 0 : record.total))}</strong></div>}</div><div className="sd-arabic-terms" lang="ar" dir="rtl"><ul><li>الضمان على المنتجات المباعة والمسجلة بهذه الفاتورة حصرياً من قبل المعرض.</li><li>البرامج والإكسسوارات والبطاريات والمواد الاستهلاكية ليست مغطاة تحت الضمان. يرجى الاحتفاظ بفاتورة المبيعات للمطالبة بالضمان.</li><li>الأجهزة الجديدة: ضمان سنة. الأجهزة المفتوحة والمجددة: ضمان 90 يوماً من تاريخ الفاتورة.</li><li>الاستبدال فقط للأجهزة التي لا تعمل عند الاستلام وتُعاد خلال 3 أيام من تاريخ الفاتورة.</li><li>يُلغى الضمان عند فتح الجهاز أو كسر الختم أو وجود ضرر مادي. قد تستغرق الصيانة 35–45 يوماً.</li><li>إذا كان الجهاز غير قابل للإصلاح، يُرد المبلغ بعد خصم 4٪ شهرياً من تاريخ الفاتورة.</li></ul></div></div></div>
    {record.memo && <p className="sd-note"><b>Notes / ملاحظات:</b> {String(record.memo)}</p>}
  </article>;
}
