"use client";
import { useState } from 'react';
import { defaultElementProperties, propertyTargets, type DocumentDesign, type ElementProperties } from '@/lib/document-design';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

export function TemplateProperties({design,onChange,selectedKey,onSelectedKeyChange,showElementPicker=true,tabs=['Text','Border','Background','Position']}:{design:DocumentDesign;onChange:(patch:Partial<DocumentDesign>)=>void;selectedKey?:string;onSelectedKeyChange?:(key:string)=>void;showElementPicker?:boolean;tabs?:Array<'Text'|'Border'|'Background'|'Position'>}) {
 const [localSelected,setLocalSelected]=useState('title');
 const [tab,setTab]=useState<'Text'|'Border'|'Background'|'Position'>('Text');
 const selected=selectedKey??localSelected;
 const setSelected=(key:string)=>{setLocalSelected(key);onSelectedKeyChange?.(key);};
 const p=design.properties[selected]||{...defaultElementProperties,top:selected.startsWith('columns.'),right:selected.startsWith('columns.'),bottom:selected.startsWith('columns.'),left:selected.startsWith('columns.'),font:design.font,size:selected==='title'?design.titleSize:selected==='company'?design.companySize:design.fontSize,color:selected==='title'||selected==='company'?design.color:'#111111',align:selected==='title'||selected==='company'?'center' as const:'left' as const};
 const update=(patch:Partial<ElementProperties>)=>onChange({properties:{...design.properties,[selected]:{...p,...patch}}});
 const check=(key:'bold'|'italic'|'underline'|'top'|'right'|'bottom'|'left'|'fill'|'hidden',label:string)=><label className="flex items-center gap-2"><input type="checkbox" checked={p[key]} onChange={e=>update({[key]:e.target.checked})}/>{label}</label>;
 const color=(key:'color'|'borderColor'|'background',label:string)=><label className="flex items-center justify-between gap-2">{label}<Input className="w-20" type="color" value={p[key]} onChange={e=>update({[key]:e.target.value})}/></label>;
 const select=(key:'align'|'vertical'|'font'|'pattern',label:string,options:string[])=><label className="grid gap-1">{label}<select className="rounded border bg-background p-2" value={p[key]} onChange={e=>update({[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{v==='solid'?'Normal':v.charAt(0).toUpperCase()+v.slice(1)}</option>)}</select></label>;
 const positionNumber=(key:'offsetX'|'offsetY'|'boxWidth'|'boxHeight',label:string,min:number,max:number)=><label className="grid gap-1">{label}<Input type="number" min={min} max={max} value={p[key]} onChange={e=>update({[key]:Math.min(max,Math.max(min,Math.round(Number(e.target.value)||0)))})}/></label>;
 return <div className="space-y-4 text-sm">
  {showElementPicker&&<label className="grid gap-1 font-medium">Element<select className="rounded border bg-background p-2" value={selected} onChange={e=>setSelected(e.target.value)}>{propertyTargets(design).map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></label>}
  <div className="flex flex-wrap gap-2">{tabs.map(t=><Button type="button" key={t} aria-pressed={tab===t} variant={tab===t?'default':'outline'} onClick={()=>setTab(t)}>{t}</Button>)}</div>
  {tab==='Text'&&<div className="grid grid-cols-2 gap-4">{select('align','Horizontal alignment',['left','center','right'])}{select('vertical','Vertical alignment',['top','middle','bottom'])}{select('font','Font',['Arial','Georgia','Verdana'])}<label>Font size<Input type="number" min={8} max={40} value={p.size} onChange={e=>update({size:Math.min(40,Math.max(8,Number(e.target.value)))})}/></label>{check('bold','Bold')}{check('italic','Italic')}{check('underline','Underline')}{color('color','Text color')}<label className="col-span-2">Minimum element height (px)<Input type="number" min={0} max={300} value={p.minHeight} onChange={e=>update({minHeight:Math.min(300,Math.max(0,Number(e.target.value)))})}/></label></div>}
  {tab==='Border'&&<div className="grid grid-cols-2 gap-4">{check('top','Top')}{check('left','Left')}{check('right','Right')}{check('bottom','Bottom')}{select('pattern','Pattern',['solid','dotted','dashed','double'])}<label className="grid gap-1">Thickness<select className="rounded border bg-background p-2" value={p.thickness} onChange={e=>update({thickness:Number(e.target.value)})}>{[0.5,1,2,3].map(v=><option key={v} value={v}>{v} pt</option>)}</select></label><label className="grid gap-1">Rounded corners<select className="rounded border bg-background p-2" value={p.radius} onChange={e=>update({radius:Number(e.target.value)})}>{[[0,'None'],[12,'Small (⅛ in)'],[24,'Medium (¼ in)'],[48,'Large (½ in)']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{color('borderColor','Border color')}</div>}
  {tab==='Background'&&<div className="space-y-4">{check('fill','Fill background')}{color('background','Background color')}</div>}
  {tab==='Position'&&<div className="space-y-4"><div className="rounded-md border p-3">{check('hidden','Remove / hide this box')}<p className="mt-1 text-xs text-muted-foreground">Uncheck this option at any time to add the box back to the template.</p></div><div className="grid grid-cols-2 gap-4">{positionNumber('offsetX','L — Left / right (px)',-1200,1200)}{positionNumber('boxHeight','H — Height (0 = auto)',0,800)}{positionNumber('boxWidth','W — Width (0 = auto)',0,1200)}{positionNumber('offsetY','D — Down / up (px)',-1600,1600)}</div><Button type="button" variant="outline" onClick={()=>update({offsetX:0,offsetY:0,boxWidth:0,boxHeight:0})}>Reset L / H / W / D</Button><p className="text-muted-foreground">Use L / H / W / D for exact box position and size, or drag movable boxes directly in the preview.</p></div>}
  <Button type="button" variant="outline" onClick={()=>{const next={...design.properties};delete next[selected];onChange({properties:next});}}>Reset element formatting</Button>
  <p className="text-muted-foreground">Formatting applies to this element in screen and print/PDF output. Edit text in Basic, Header, Columns, or Footer.</p>
 </div>;
}
